Remove unnecessary call to bytesize
We're seeing errors in the logs "(gds) Authentication failure! undefined
method 'bytesize' for nil: NoMethodError, undefined method 'bytesize'
for nil"

This call to bytesize is unguarded, but the result also isn't used, so
can be removed. The previous call (in the same method) is guarded.

Not all the logged errors are for this app, so if we still see them then
this wasn't the cause, or wasn't the only one.